
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SM_600.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SM_600.ModelInput sampleData = new SM_600.ModelInput()
            {
                User_Input = @"Are there any discounts or bonus for cancelling bookings at short notice?",
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual Classification with predicted Classification from sample data...\n\n");


            Console.WriteLine($"Classification: {@"ExistingBooking_CancelBooking"}");
            Console.WriteLine($"User_Input: {@"Are there any discounts or bonus for cancelling bookings at short notice?"}");


            var sortedScoresWithLabel = SM_600.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
