name: "Process Latest Release"

on:
  workflow_dispatch: # Trigger manually

jobs:
  process-latest-release:
    name: "Process Latest Release"
    runs-on: "ubuntu-latest"

    steps:
            # Step 1: Checkout repository
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: Execute
        run: |
          chmod +x ./get_latest_release.sh
          ./get_latest_release.sh
        shell: bash
